### ISSUE TITLE
Please add "Page Attributes" panel to Edit Domain Name Pages

### ISSUE THREAD

**Issue by geraldsnm** [pronamic/wp-pronamic-domain-mapping#2]
Hi,
Domain Name Pages has almost every feature of the WP Core "Pages", except for one of the most important features the "Page Attributes" panel, which gives you the ability to set the template for the page. 

![screen shot 2017-09-20 at 11 03 38 am](https://user-images.githubusercontent.com/3663716/30651386-8fb08736-9df3-11e7-8a0d-b33b7f63c340.png)

**Comment by geraldsnm** [comment]
Hi Pronamic Developers, 
I'd like to try and get some confirmation that this plugin is still being given any attention or any thoughts to revisit the code for future development.

Our company would really like to use this plugin-in, if you can fix the issue (#2) WRT adding "Page Attributes" panel. 

In fact, we'd even be willing to pay a substantial amount if this feature could be added. But in order to for us to maintain interest in this, I need to know someone is looking into this issue and would need some sort of reply or confirmation that this issue hasn't fallen on deaf ears.

Thansk

**Comment by geraldsnm** [comment]
also (and I hope this goes without saying) but this plug-in should also be tested & certified for the latest version of WordPress when (at the time) it's being updated to add this new feature request.

Thanks

**Comment by remcotolsma** [comment]
This was just added in: https://github.com/pronamic/wp-pronamic-domain-mapping/commit/bcae104e5909302f2dc9a90dba658c14f93a12e0.

Please note that you have to specify to post type in custom templates:

```php
<?php
/*
Template Name: Full-width layout
Template Post Type: post, page, product, pronamic_domain_page
*/
```

Source: https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/

```php
add_post_type_support( 'pronamic_domain_page', 'page-attributes' );
```

**Comment by geraldsnm** [comment]
Question: When I try to put in a new domain, with a permalink of:

http://www.newdomain.com/

My original domain gets overwritten by the new template of the new domain.

If I try to add both domains to Pronamic "Domain Name Pages" so that I can set the templates independently for both domains, then all of my other pages disappear from WP "Pages" panel.
