### ISSUE TITLE
Update screenshots?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-domain-mapping#4]
```
[WordPress Plugin][2554987] pronamic-domain-mapping: Deploy from Git (2.0.1)
```

https://wordpress.org/plugins/pronamic-domain-mapping/

Note from @LeoOosterloo:

> Die screenshots moeten ook even worden bij gewerkt, of niet?

**Comment by LeoOosterloo** [comment]
Volgens mij doen we niets (actiefs) met deze plugin. Updaten van screenshots lijkt me dan ook overbodig.
